### ISSUE TITLE
HR IQ Quiz

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#12]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

How it appears online:
![screen shot 2016-02-11 at 1 43 45 am](https://cloud.githubusercontent.com/assets/7436666/12976167/fdb61c7e-d076-11e5-80cc-aafe3dd4c627.png)
Can we line up the "Results" button like it is on the psd?

How it should be:
![screen shot 2016-02-11 at 1 43 52 am](https://cloud.githubusercontent.com/assets/7436666/12976168/fdbbb04e-d076-11e5-9475-46c64a1f82b2.png)

**Comment by KWenn** [comment]
Ok, updated.

**Comment by Sramos9191** [comment]
@KWenn  it still looks like it's lined up more with the end then under the A & B

![screen shot 2016-02-13 at 8 29 53 pm](https://cloud.githubusercontent.com/assets/7436666/13031857/a2f29c56-d290-11e5-85bd-af58e4ccc875.png)

**Comment by KWenn** [comment]
Updated

**Comment by Sramos9191** [comment]
looks better
