### ISSUE TITLE
HR IQ Quiz (cont.)

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#13]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

D, doesn't appear to be finished.

![screen shot 2016-02-11 at 1 46 53 am](https://cloud.githubusercontent.com/assets/7436666/12976203/39092d2a-d077-11e5-8bd2-55f45be784da.png)

**Comment by KWenn** [comment]
Updated.
