### ISSUE TITLE
Events Calendar

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#14]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

how it appears online:
![screen shot 2016-02-11 at 1 52 05 am](https://cloud.githubusercontent.com/assets/7436666/12976225/59dea4e4-d077-11e5-8114-1ce23fac74a6.png)
Event Name H4
Description along with info are considered Paragraph tags

"WHEN, WHERE, CONTACT & PRICE" should be:
font-size: 1.2em
line-height: 100%
font: lato
font-style: black
color: navy

How it should appear:
![screen shot 2016-02-11 at 1 52 13 am](https://cloud.githubusercontent.com/assets/7436666/12976226/59decd98-d077-11e5-9fc5-b76d6917454a.png)

**Comment by KWenn** [comment]
I updated it but left the spacing toward the bottom because it is a plugin (The Event Calendar) and it would have required extensive manipulation of the code to achieve the layout perfectly. Hopefully, this will be sufficient. 

updated

**Comment by Sramos9191** [comment]
looks good
