### ISSUE TITLE
Blog Categories

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#15]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

Can we remove the categories from the sidebar ? And side bar titles should be H6's & bullet points H7's
![screen shot 2016-02-11 at 1 58 19 am](https://cloud.githubusercontent.com/assets/7436666/12976308/f05b2334-d077-11e5-928d-1e89781271f6.png)

**Comment by KWenn** [comment]
The categories were added per the request of Suzanne and Channelle at Bertz-Rosa. Originally there was to be a HR Bulletins section on the backend but the customer changed their mind and asked that they be included on the front end mixed with the HR News. They also requested that the HR Bulletins have a separate designation with each post. The categories are to make it sortable. I can style them to match Recent Posts but they need to stay.

**Comment by Sramos9191** [comment]
Fair enough. I didn't see that mentioned in the notes on Basecamp.
