### ISSUE TITLE
Contact (cont.)

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#17]
OS X El Capitan 
Version 10.11.3
Firefox 44.0.1

How it appears online:
![screen shot 2016-02-11 at 1 59 33 am](https://cloud.githubusercontent.com/assets/7436666/12976422/cf4d1e9e-d078-11e5-994f-f1b6f063ed58.png)
Send Us a Message is H3
What are you interested in? H4 Char Grey
Checkboxes P color: Char Grey

How it should be:
![screen shot 2016-02-11 at 1 59 42 am](https://cloud.githubusercontent.com/assets/7436666/12976423/cf5094d4-d078-11e5-8d1d-8c4baf7dd186.png)

**Comment by KWenn** [comment]
I avoided using the p tags because they made the inputs look too big. I added them but now the size is much bigger than the design calls for. All that is supposed to be Char Grey was already set to Char Grey. I am not sure if I am missing something here.

**Comment by Sramos9191** [comment]
@KWenn the input fields on the contact form look huge, was that what you were talking about?

**Comment by KWenn** [comment]
yes, by adding the p tag, it does that.

**Comment by Sramos9191** [comment]
Let’s leave it - so I can tag Miguel and see what he wants to do about it.

**Comment by KWenn** [comment]
ok
