### ISSUE TITLE
Drop Down Menu Issue

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#2]
OS X El Capitan
Version 10.11.3

Firefox 44.0.1

How it's supposed to look:
![screen shot 2016-02-10 at 10 38 08 pm](https://cloud.githubusercontent.com/assets/7436666/12971011/a86be086-d04a-11e5-9c90-2c11ee6f98ef.png)

How it looks online: 
![screen shot 2016-02-10 at 10 01 22 pm](https://cloud.githubusercontent.com/assets/7436666/12971010/a83d7584-d04a-11e5-9db4-d59e68f7832d.png)

**Comment by KWenn** [comment]
The submenu names are too long to fit in a square that is the same size is the main menu item but I imagine you know that. I squared the edges to match, updated the colors and added the triangle at the top of the submenu. I did change the hover color to match the color in the image, however, it doesn't look the same as the image. 

Updated

**Comment by Sramos9191** [comment]
it looks great
