### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#26]
OS X El Capitan 
Version 10.11.3
Firefox 44.0.1

_how it appears_
![screen shot 2016-02-11 at 12 16 16 am](https://cloud.githubusercontent.com/assets/7436666/12977910/8ecca844-d082-11e5-9c9f-b62697fb3262.png)
"Forgot Your Password" color: navy - H3
"Enter your email" color: black - H4
Please make text field the same width as the button

_how it should be_
![screen shot 2016-02-11 at 12 16 23 am](https://cloud.githubusercontent.com/assets/7436666/12977909/8eb180c8-d082-11e5-9605-1d831307dbdb.png)

**Comment by KWenn** [comment]
Updated to match. The content in the paragraph tags along with the <h3> is correct in the code as specified on the style guide but does not match exactly visually.

**Comment by Sramos9191** [comment]
@KWenn can you please stop closing the issues until I've had a chance to check them and make sure they've been completed. If you can just comment that you've done it, I'll close them out once I've checked. Thank you!

**Comment by KWenn** [comment]
@Sramos9191 Oh, sorry. This is the first QA I have been through with Shift3 and wasn't sure about protocol. I figured they would have just been re-opened. I will not close them from now on.

**Comment by Sramos9191** [comment]
@KWenn That's alright. So you're saying that the code matches the style guide but it isn't visually matching up?

**Comment by KWenn** [comment]
Correct.
