### ISSUE TITLE
Email Sign Up

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#27]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

**please add a teal border around the text fields**

_how it should be_
![screen shot 2016-02-11 at 12 20 33 am](https://cloud.githubusercontent.com/assets/7436666/12978027/538beff0-d083-11e5-9f6d-692159595d66.png)

**Comment by KWenn** [comment]
I added the board, the hover on the button and the rounded the edges slightly on the inputs.
