### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#28]
@KWenn is the navigation doing this for you also? it wasn't like that before but it is now.

![screen shot 2016-02-13 at 8 04 41 pm](https://cloud.githubusercontent.com/assets/7436666/13031779/14a18f82-d28d-11e5-8ec5-8efd8c8ba670.png)

**Comment by KWenn** [comment]
I set the display to block so I can work on it. I started working on the arrow but because it is a dynamic it needs to be coded into the nav walker. So I just left it to work on later while I get the rest of these issues handled.

**Comment by Sramos9191** [comment]
Okay, sounds good. Thanks

**Comment by KWenn** [comment]
updated
