### ISSUE TITLE
Footer Link Color

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#4]
OS X El Capitan
Version 10.11.3
Firefox 44.0.1

Footer link color should be Teal #429895

How it's displayed on the website:
![screen shot 2016-02-10 at 11 43 21 pm](https://cloud.githubusercontent.com/assets/7436666/12975134/2055bb1c-d06e-11e5-99cc-668b8c883828.png)

**Comment by KWenn** [comment]
updated
