### ISSUE TITLE
Client Log In Issue

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#5]
OS X El Capitan
Version 10.11.3
Firefox 44.0.1

How it should look:
![screen shot 2016-02-11 at 12 14 14 am](https://cloud.githubusercontent.com/assets/7436666/12975349/b4cd4b74-d06f-11e5-9f50-e4116aa227ba.png)

What the website displays:
![screen shot 2016-02-11 at 12 14 04 am](https://cloud.githubusercontent.com/assets/7436666/12975348/b4ca8c7c-d06f-11e5-84b6-dabbb229887e.png)
the color of the button should be #076a8a
line the question mark at the end of "forgot password?" with the end of the input fields

**Comment by KWenn** [comment]
My style guide shows it references the B listing and background color: Navy (off) Teal (hover), I did update it to the styles referenced. 
<img width="471" alt="screen shot 2016-02-13 at 9 36 30 pm" src="https://cloud.githubusercontent.com/assets/9420221/13032065/f59b1682-d299-11e5-90ee-30942fc65190.png">
