### ISSUE TITLE
Space between footer on HR Business Partner

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#6]
OS X El Capitan
 Version 10.11.3
Firefox 44.0.1

What the website displays:
![screen shot 2016-02-11 at 1 06 15 am](https://cloud.githubusercontent.com/assets/7436666/12975477/e61e1e28-d070-11e5-876f-d753fab0ae16.png)

How it should be:
![screen shot 2016-02-11 at 1 06 23 am](https://cloud.githubusercontent.com/assets/7436666/12975478/e61fe244-d070-11e5-903a-4b5475fdb677.png)

Can you add some space between the footer and the relevant topics

**Comment by KWenn** [comment]
updated
