### ISSUE TITLE
Team Issue

### ISSUE THREAD

**Issue by Sramos9191** [Shift3/new-sierra#8]
OS X El Capitan 
Version 10.11.3
Firefox 44.0.1

How it's displayed on the website:
![screen shot 2016-02-11 at 1 36 25 am](https://cloud.githubusercontent.com/assets/7436666/12975909/b483e4de-d074-11e5-836d-0c6e59e776cb.png)
the psd's show the image taking up the full space so that the content is centered under it, can we make the image the same width as the other images or center it over the content just so it's consistent with the rest of the images.

**Comment by KWenn** [comment]
the original psd files were low resolution. I lifted this image from it and if I increased it's size it would have pixelated. To avoid that, I kept the log the same size and increased the overall size of the image which caused it to fill in the empty space.

**Comment by Sramos9191** [comment]
perfect
